# Stage 1: Build
FROM node:16.13.1 AS build
WORKDIR /usr/app
COPY package.json package-lock.json ./
RUN npm install
COPY . . 
RUN npm run build

# Stage 2: Serve
FROM nginx:1.21-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
EXPOSE 80
