pipeline {
    agent any
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }    
    stages {
        stage("SonarQube Analysis") {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh ''' 
                        $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=nodejs \
                        -Dsonar.projectKey=nodekey
                    '''
                }
            }
        }
        stage("Build Docker Image") {
            steps {
                script {
                    sh "docker build -t react-app:v1 -f Dockerfile ."
                    sh "docker images"
                }
            }
        }
        stage("Run Docker Container") {
            steps {
                script {
                    sh "docker compose up -d"
                    sh "docker ps"
                }
            }
        }
    }
}

        // stage("Deploy"){
        //     steps{
        //         sh "cd coit-frontend && cp build/* /var/www/html/"
        //     }
        // }
        
    
   // post{
        // success{
        //     archiveArtifacts artifacts: '**/build', followSymlinks: false
        // }
        // failure{
        //     emailext body: '''Jenkins has failed to build the Job. Please find the information below.

        //                     Name of the Job: ${JOB_NAME}
        //                     Build that failed: ${BUILD_NUMBER}

        //                     Please check the logs at ${BUILD_URL}


        //                     Thanks
        //                     Jenkins''', subject: 'Failed ${JOB_NAME}', to: 'basil@coit.io'
        // }
   // }

