pipeline{
    agent any
    stages{
        stage("Image"){
            steps{
               docker image rm react-app:v-1
               docker build -t react-app:v-1 -f Dockerfile .
               docker images
            }
        }
        stage("Docker Container"){
            steps{
                docker compose up -d
                docker ps
            }
        }
        // stage("Deploy"){
        //     steps{
        //         sh "cd coit-frontend && cp build/* /var/www/html/"
        //     }
        // }
        
    }
   // post{
        // success{
        //     archiveArtifacts artifacts: '**/build', followSymlinks: false
        // }
        // failure{
        //     emailext body: '''Jenkins has failed to build the Job. Please find the information below.

        //                     Name of the Job: ${JOB_NAME}
        //                     Build that failed: ${BUILD_NUMBER}

        //                     Please check the logs at ${BUILD_URL}


        //                     Thanks
        //                     Jenkins''', subject: 'Failed ${JOB_NAME}', to: 'basil@coit.io'
        // }
   // }
}
